name = "push-proxy"
compatibility_date = "2024-01-01"
node_compat = true

[build]
command = ""

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.mjs"]

[vars]
# 可以在這裡設定允許的 site keys (用逗號分隔)
# ALLOWED_SITE_KEYS = "site1,site2,site3"

# 開發環境設定
[env.preview.vars]
# ALLOWED_SITE_KEYS = "dev-site-key"

# 生產環境設定
[env.production.vars]
# ALLOWED_SITE_KEYS = "prod-site-key-1,prod-site-key-2"